# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class GenderType(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    FEMALE = "female"
    MALE = "male"
    UNKNOWN = "unknown"
    NONBINARY = "nonbinary"

    def __init__(self):  # noqa: E501
        """GenderType - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'GenderType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GenderType of this GenderType.  # noqa: E501
        :rtype: GenderType
        """
        return util.deserialize_model(dikt, cls)
