# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.healthcare_provider import HealthcareProvider  # noqa: F401,E501
from openapi_server.models.organization_type import OrganizationType  # noqa: F401,E501
from openapi_server import util


class HCO(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, healthcare_provider_id: str=None, firstname: str=None, surname: str=None, bin: str=None, organization_type: OrganizationType=None):  # noqa: E501
        """HCO - a model defined in OpenAPI

        :param healthcare_provider_id: The healthcare_provider_id of this HCO.  # noqa: E501
        :type healthcare_provider_id: str
        :param firstname: The firstname of this HCO.  # noqa: E501
        :type firstname: str
        :param surname: The surname of this HCO.  # noqa: E501
        :type surname: str
        :param bin: The bin of this HCO.  # noqa: E501
        :type bin: str
        :param organization_type: The organization_type of this HCO.  # noqa: E501
        :type organization_type: OrganizationType
        """
        self.openapi_types = {
            'healthcare_provider_id': str,
            'firstname': str,
            'surname': str,
            'bin': str,
            'organization_type': OrganizationType
        }

        self.attribute_map = {
            'healthcare_provider_id': 'healthcare_provider_id',
            'firstname': 'firstname',
            'surname': 'surname',
            'bin': 'bin',
            'organization_type': 'organization_type'
        }

        self._healthcare_provider_id = healthcare_provider_id
        self._firstname = firstname
        self._surname = surname
        self._bin = bin
        self._organization_type = organization_type

    @classmethod
    def from_dict(cls, dikt) -> 'HCO':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The HCO of this HCO.  # noqa: E501
        :rtype: HCO
        """
        return util.deserialize_model(dikt, cls)

    @property
    def healthcare_provider_id(self) -> str:
        """Gets the healthcare_provider_id of this HCO.


        :return: The healthcare_provider_id of this HCO.
        :rtype: str
        """
        return self._healthcare_provider_id

    @healthcare_provider_id.setter
    def healthcare_provider_id(self, healthcare_provider_id: str):
        """Sets the healthcare_provider_id of this HCO.


        :param healthcare_provider_id: The healthcare_provider_id of this HCO.
        :type healthcare_provider_id: str
        """

        self._healthcare_provider_id = healthcare_provider_id

    @property
    def firstname(self) -> str:
        """Gets the firstname of this HCO.


        :return: The firstname of this HCO.
        :rtype: str
        """
        return self._firstname

    @firstname.setter
    def firstname(self, firstname: str):
        """Sets the firstname of this HCO.


        :param firstname: The firstname of this HCO.
        :type firstname: str
        """

        self._firstname = firstname

    @property
    def surname(self) -> str:
        """Gets the surname of this HCO.


        :return: The surname of this HCO.
        :rtype: str
        """
        return self._surname

    @surname.setter
    def surname(self, surname: str):
        """Sets the surname of this HCO.


        :param surname: The surname of this HCO.
        :type surname: str
        """

        self._surname = surname

    @property
    def bin(self) -> str:
        """Gets the bin of this HCO.

        the business identification number  # noqa: E501

        :return: The bin of this HCO.
        :rtype: str
        """
        return self._bin

    @bin.setter
    def bin(self, bin: str):
        """Sets the bin of this HCO.

        the business identification number  # noqa: E501

        :param bin: The bin of this HCO.
        :type bin: str
        """

        self._bin = bin

    @property
    def organization_type(self) -> OrganizationType:
        """Gets the organization_type of this HCO.


        :return: The organization_type of this HCO.
        :rtype: OrganizationType
        """
        return self._organization_type

    @organization_type.setter
    def organization_type(self, organization_type: OrganizationType):
        """Sets the organization_type of this HCO.


        :param organization_type: The organization_type of this HCO.
        :type organization_type: OrganizationType
        """

        self._organization_type = organization_type
