# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class Physician(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, healthcare_provider_id=None, name=None, creation_date=None, deactivation_date=None, firstname=None, lastname=None, specialty=None, licence_number=None, licence_date=None):  # noqa: E501
        """Physician - a model defined in OpenAPI

        :param healthcare_provider_id: The healthcare_provider_id of this Physician.  # noqa: E501
        :type healthcare_provider_id: str
        :param name: The name of this Physician.  # noqa: E501
        :type name: str
        :param creation_date: The creation_date of this Physician.  # noqa: E501
        :type creation_date: date
        :param deactivation_date: The deactivation_date of this Physician.  # noqa: E501
        :type deactivation_date: date
        :param firstname: The firstname of this Physician.  # noqa: E501
        :type firstname: str
        :param lastname: The lastname of this Physician.  # noqa: E501
        :type lastname: str
        :param specialty: The specialty of this Physician.  # noqa: E501
        :type specialty: str
        :param licence_number: The licence_number of this Physician.  # noqa: E501
        :type licence_number: str
        :param licence_date: The licence_date of this Physician.  # noqa: E501
        :type licence_date: date
        """
        self.openapi_types = {
            'healthcare_provider_id': str,
            'name': str,
            'creation_date': date,
            'deactivation_date': date,
            'firstname': str,
            'lastname': str,
            'specialty': str,
            'licence_number': str,
            'licence_date': date
        }

        self.attribute_map = {
            'healthcare_provider_id': 'healthcare_provider_id',
            'name': 'name',
            'creation_date': 'creation_date',
            'deactivation_date': 'deactivation_date',
            'firstname': 'firstname',
            'lastname': 'lastname',
            'specialty': 'specialty',
            'licence_number': 'licence_number',
            'licence_date': 'licence_date'
        }

        self._healthcare_provider_id = healthcare_provider_id
        self._name = name
        self._creation_date = creation_date
        self._deactivation_date = deactivation_date
        self._firstname = firstname
        self._lastname = lastname
        self._specialty = specialty
        self._licence_number = licence_number
        self._licence_date = licence_date

    @classmethod
    def from_dict(cls, dikt) -> 'Physician':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Physician of this Physician.  # noqa: E501
        :rtype: Physician
        """
        return util.deserialize_model(dikt, cls)

    @property
    def healthcare_provider_id(self):
        """Gets the healthcare_provider_id of this Physician.


        :return: The healthcare_provider_id of this Physician.
        :rtype: str
        """
        return self._healthcare_provider_id

    @healthcare_provider_id.setter
    def healthcare_provider_id(self, healthcare_provider_id):
        """Sets the healthcare_provider_id of this Physician.


        :param healthcare_provider_id: The healthcare_provider_id of this Physician.
        :type healthcare_provider_id: str
        """

        self._healthcare_provider_id = healthcare_provider_id

    @property
    def name(self):
        """Gets the name of this Physician.


        :return: The name of this Physician.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Physician.


        :param name: The name of this Physician.
        :type name: str
        """

        self._name = name

    @property
    def creation_date(self):
        """Gets the creation_date of this Physician.


        :return: The creation_date of this Physician.
        :rtype: date
        """
        return self._creation_date

    @creation_date.setter
    def creation_date(self, creation_date):
        """Sets the creation_date of this Physician.


        :param creation_date: The creation_date of this Physician.
        :type creation_date: date
        """

        self._creation_date = creation_date

    @property
    def deactivation_date(self):
        """Gets the deactivation_date of this Physician.


        :return: The deactivation_date of this Physician.
        :rtype: date
        """
        return self._deactivation_date

    @deactivation_date.setter
    def deactivation_date(self, deactivation_date):
        """Sets the deactivation_date of this Physician.


        :param deactivation_date: The deactivation_date of this Physician.
        :type deactivation_date: date
        """

        self._deactivation_date = deactivation_date

    @property
    def firstname(self):
        """Gets the firstname of this Physician.


        :return: The firstname of this Physician.
        :rtype: str
        """
        return self._firstname

    @firstname.setter
    def firstname(self, firstname):
        """Sets the firstname of this Physician.


        :param firstname: The firstname of this Physician.
        :type firstname: str
        """

        self._firstname = firstname

    @property
    def lastname(self):
        """Gets the lastname of this Physician.


        :return: The lastname of this Physician.
        :rtype: str
        """
        return self._lastname

    @lastname.setter
    def lastname(self, lastname):
        """Sets the lastname of this Physician.


        :param lastname: The lastname of this Physician.
        :type lastname: str
        """

        self._lastname = lastname

    @property
    def specialty(self):
        """Gets the specialty of this Physician.


        :return: The specialty of this Physician.
        :rtype: str
        """
        return self._specialty

    @specialty.setter
    def specialty(self, specialty):
        """Sets the specialty of this Physician.


        :param specialty: The specialty of this Physician.
        :type specialty: str
        """

        self._specialty = specialty

    @property
    def licence_number(self):
        """Gets the licence_number of this Physician.


        :return: The licence_number of this Physician.
        :rtype: str
        """
        return self._licence_number

    @licence_number.setter
    def licence_number(self, licence_number):
        """Sets the licence_number of this Physician.


        :param licence_number: The licence_number of this Physician.
        :type licence_number: str
        """

        self._licence_number = licence_number

    @property
    def licence_date(self):
        """Gets the licence_date of this Physician.


        :return: The licence_date of this Physician.
        :rtype: date
        """
        return self._licence_date

    @licence_date.setter
    def licence_date(self, licence_date):
        """Sets the licence_date of this Physician.


        :param licence_date: The licence_date of this Physician.
        :type licence_date: date
        """

        self._licence_date = licence_date
