# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class WebUser(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, user_id: str=None, client_id: str=None, healthcare_provider_id: str=None, status: str=None, created_date: date=None, type: str=None, created_at: str=None):  # noqa: E501
        """WebUser - a model defined in OpenAPI

        :param user_id: The user_id of this WebUser.  # noqa: E501
        :type user_id: str
        :param client_id: The client_id of this WebUser.  # noqa: E501
        :type client_id: str
        :param healthcare_provider_id: The healthcare_provider_id of this WebUser.  # noqa: E501
        :type healthcare_provider_id: str
        :param status: The status of this WebUser.  # noqa: E501
        :type status: str
        :param created_date: The created_date of this WebUser.  # noqa: E501
        :type created_date: date
        :param type: The type of this WebUser.  # noqa: E501
        :type type: str
        :param created_at: The created_at of this WebUser.  # noqa: E501
        :type created_at: str
        """
        self.openapi_types = {
            'user_id': str,
            'client_id': str,
            'healthcare_provider_id': str,
            'status': str,
            'created_date': date,
            'type': str,
            'created_at': str
        }

        self.attribute_map = {
            'user_id': 'user_id',
            'client_id': 'client_id',
            'healthcare_provider_id': 'healthcare_provider_id',
            'status': 'status',
            'created_date': 'created_date',
            'type': 'type',
            'created_at': 'created_at'
        }

        self._user_id = user_id
        self._client_id = client_id
        self._healthcare_provider_id = healthcare_provider_id
        self._status = status
        self._created_date = created_date
        self._type = type
        self._created_at = created_at

    @classmethod
    def from_dict(cls, dikt) -> 'WebUser':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The WebUser of this WebUser.  # noqa: E501
        :rtype: WebUser
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user_id(self) -> str:
        """Gets the user_id of this WebUser.


        :return: The user_id of this WebUser.
        :rtype: str
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id: str):
        """Sets the user_id of this WebUser.


        :param user_id: The user_id of this WebUser.
        :type user_id: str
        """

        self._user_id = user_id

    @property
    def client_id(self) -> str:
        """Gets the client_id of this WebUser.


        :return: The client_id of this WebUser.
        :rtype: str
        """
        return self._client_id

    @client_id.setter
    def client_id(self, client_id: str):
        """Sets the client_id of this WebUser.


        :param client_id: The client_id of this WebUser.
        :type client_id: str
        """

        self._client_id = client_id

    @property
    def healthcare_provider_id(self) -> str:
        """Gets the healthcare_provider_id of this WebUser.


        :return: The healthcare_provider_id of this WebUser.
        :rtype: str
        """
        return self._healthcare_provider_id

    @healthcare_provider_id.setter
    def healthcare_provider_id(self, healthcare_provider_id: str):
        """Sets the healthcare_provider_id of this WebUser.


        :param healthcare_provider_id: The healthcare_provider_id of this WebUser.
        :type healthcare_provider_id: str
        """

        self._healthcare_provider_id = healthcare_provider_id

    @property
    def status(self) -> str:
        """Gets the status of this WebUser.


        :return: The status of this WebUser.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this WebUser.


        :param status: The status of this WebUser.
        :type status: str
        """

        self._status = status

    @property
    def created_date(self) -> date:
        """Gets the created_date of this WebUser.


        :return: The created_date of this WebUser.
        :rtype: date
        """
        return self._created_date

    @created_date.setter
    def created_date(self, created_date: date):
        """Sets the created_date of this WebUser.


        :param created_date: The created_date of this WebUser.
        :type created_date: date
        """

        self._created_date = created_date

    @property
    def type(self) -> str:
        """Gets the type of this WebUser.


        :return: The type of this WebUser.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this WebUser.


        :param type: The type of this WebUser.
        :type type: str
        """

        self._type = type

    @property
    def created_at(self) -> str:
        """Gets the created_at of this WebUser.


        :return: The created_at of this WebUser.
        :rtype: str
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at: str):
        """Sets the created_at of this WebUser.


        :param created_at: The created_at of this WebUser.
        :type created_at: str
        """

        self._created_at = created_at
