# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class ServiceLanguage(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    EN = "en"
    FR = "fr"

    def __init__(self):  # noqa: E501
        """ServiceLanguage - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'ServiceLanguage':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ServiceLanguage of this ServiceLanguage.  # noqa: E501
        :rtype: ServiceLanguage
        """
        return util.deserialize_model(dikt, cls)
