#!/usr/bin/env python3

import connexion

from openapi_server import encoder

## FIXME Note: this won't work now that we're not using autogenerated api routes.

def main():
    app = connexion.App(__name__, specification_dir='./openapi/')
    app.app.json_encoder = encoder.JSONEncoder
    app.add_api('openapi.yaml', arguments={'title': 'MyPHR API'})
    app.run(port=8080)


if __name__ == '__main__':
    main()
