# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class HCO(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, healthcare_provider_id=None, name=None, start_date=None, end_date=None, bin=None, organization_type=None):  # noqa: E501
        """HCO - a model defined in OpenAPI

        :param healthcare_provider_id: The healthcare_provider_id of this HCO.  # noqa: E501
        :type healthcare_provider_id: str
        :param name: The name of this HCO.  # noqa: E501
        :type name: str
        :param start_date: The start_date of this HCO.  # noqa: E501
        :type start_date: date
        :param end_date: The end_date of this HCO.  # noqa: E501
        :type end_date: date
        :param bin: The bin of this HCO.  # noqa: E501
        :type bin: str
        :param organization_type: The organization_type of this HCO.  # noqa: E501
        :type organization_type: str
        """
        self.openapi_types = {
            'healthcare_provider_id': str,
            'name': str,
            'start_date': date,
            'end_date': date,
            'bin': str,
            'organization_type': str
        }

        self.attribute_map = {
            'healthcare_provider_id': 'healthcare_provider_id',
            'name': 'name',
            'start_date': 'start_date',
            'end_date': 'end_date',
            'bin': 'bin',
            'organization_type': 'organization_type'
        }

        self._healthcare_provider_id = healthcare_provider_id
        self._name = name
        self._start_date = start_date
        self._end_date = end_date
        self._bin = bin
        self._organization_type = organization_type

    @classmethod
    def from_dict(cls, dikt) -> 'HCO':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The HCO of this HCO.  # noqa: E501
        :rtype: HCO
        """
        return util.deserialize_model(dikt, cls)

    @property
    def healthcare_provider_id(self):
        """Gets the healthcare_provider_id of this HCO.


        :return: The healthcare_provider_id of this HCO.
        :rtype: str
        """
        return self._healthcare_provider_id

    @healthcare_provider_id.setter
    def healthcare_provider_id(self, healthcare_provider_id):
        """Sets the healthcare_provider_id of this HCO.


        :param healthcare_provider_id: The healthcare_provider_id of this HCO.
        :type healthcare_provider_id: str
        """

        self._healthcare_provider_id = healthcare_provider_id

    @property
    def name(self):
        """Gets the name of this HCO.


        :return: The name of this HCO.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this HCO.


        :param name: The name of this HCO.
        :type name: str
        """

        self._name = name

    @property
    def start_date(self):
        """Gets the start_date of this HCO.


        :return: The start_date of this HCO.
        :rtype: date
        """
        return self._start_date

    @start_date.setter
    def start_date(self, start_date):
        """Sets the start_date of this HCO.


        :param start_date: The start_date of this HCO.
        :type start_date: date
        """

        self._start_date = start_date

    @property
    def end_date(self):
        """Gets the end_date of this HCO.


        :return: The end_date of this HCO.
        :rtype: date
        """
        return self._end_date

    @end_date.setter
    def end_date(self, end_date):
        """Sets the end_date of this HCO.


        :param end_date: The end_date of this HCO.
        :type end_date: date
        """

        self._end_date = end_date

    @property
    def bin(self):
        """Gets the bin of this HCO.

        the business identification number  # noqa: E501

        :return: The bin of this HCO.
        :rtype: str
        """
        return self._bin

    @bin.setter
    def bin(self, bin):
        """Sets the bin of this HCO.

        the business identification number  # noqa: E501

        :param bin: The bin of this HCO.
        :type bin: str
        """

        self._bin = bin

    @property
    def organization_type(self):
        """Gets the organization_type of this HCO.


        :return: The organization_type of this HCO.
        :rtype: str
        """
        return self._organization_type

    @organization_type.setter
    def organization_type(self, organization_type):
        """Sets the organization_type of this HCO.


        :param organization_type: The organization_type of this HCO.
        :type organization_type: str
        """

        self._organization_type = organization_type
