# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class Physician(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, healthcare_provider_id=None, name=None, start_date=None, end_date=None, firstname=None, surname=None, specialty=None, license_number=None, license_date=None):  # noqa: E501
        """Physician - a model defined in OpenAPI

        :param healthcare_provider_id: The healthcare_provider_id of this Physician.  # noqa: E501
        :type healthcare_provider_id: str
        :param name: The name of this Physician.  # noqa: E501
        :type name: str
        :param start_date: The start_date of this Physician.  # noqa: E501
        :type start_date: date
        :param end_date: The end_date of this Physician.  # noqa: E501
        :type end_date: date
        :param firstname: The firstname of this Physician.  # noqa: E501
        :type firstname: str
        :param surname: The surname of this Physician.  # noqa: E501
        :type surname: str
        :param specialty: The specialty of this Physician.  # noqa: E501
        :type specialty: str
        :param license_number: The license_number of this Physician.  # noqa: E501
        :type license_number: str
        :param license_date: The license_date of this Physician.  # noqa: E501
        :type license_date: date
        """
        self.openapi_types = {
            'healthcare_provider_id': str,
            'name': str,
            'start_date': date,
            'end_date': date,
            'firstname': str,
            'surname': str,
            'specialty': str,
            'license_number': str,
            'license_date': date
        }

        self.attribute_map = {
            'healthcare_provider_id': 'healthcare_provider_id',
            'name': 'name',
            'start_date': 'start_date',
            'end_date': 'end_date',
            'firstname': 'firstname',
            'surname': 'surname',
            'specialty': 'specialty',
            'license_number': 'license_number',
            'license_date': 'license_date'
        }

        self._healthcare_provider_id = healthcare_provider_id
        self._name = name
        self._start_date = start_date
        self._end_date = end_date
        self._firstname = firstname
        self._surname = surname
        self._specialty = specialty
        self._license_number = license_number
        self._license_date = license_date

    @classmethod
    def from_dict(cls, dikt) -> 'Physician':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Physician of this Physician.  # noqa: E501
        :rtype: Physician
        """
        return util.deserialize_model(dikt, cls)

    @property
    def healthcare_provider_id(self):
        """Gets the healthcare_provider_id of this Physician.


        :return: The healthcare_provider_id of this Physician.
        :rtype: str
        """
        return self._healthcare_provider_id

    @healthcare_provider_id.setter
    def healthcare_provider_id(self, healthcare_provider_id):
        """Sets the healthcare_provider_id of this Physician.


        :param healthcare_provider_id: The healthcare_provider_id of this Physician.
        :type healthcare_provider_id: str
        """

        self._healthcare_provider_id = healthcare_provider_id

    @property
    def name(self):
        """Gets the name of this Physician.


        :return: The name of this Physician.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Physician.


        :param name: The name of this Physician.
        :type name: str
        """

        self._name = name

    @property
    def start_date(self):
        """Gets the start_date of this Physician.


        :return: The start_date of this Physician.
        :rtype: date
        """
        return self._start_date

    @start_date.setter
    def start_date(self, start_date):
        """Sets the start_date of this Physician.


        :param start_date: The start_date of this Physician.
        :type start_date: date
        """

        self._start_date = start_date

    @property
    def end_date(self):
        """Gets the end_date of this Physician.


        :return: The end_date of this Physician.
        :rtype: date
        """
        return self._end_date

    @end_date.setter
    def end_date(self, end_date):
        """Sets the end_date of this Physician.


        :param end_date: The end_date of this Physician.
        :type end_date: date
        """

        self._end_date = end_date

    @property
    def firstname(self):
        """Gets the firstname of this Physician.


        :return: The firstname of this Physician.
        :rtype: str
        """
        return self._firstname

    @firstname.setter
    def firstname(self, firstname):
        """Sets the firstname of this Physician.


        :param firstname: The firstname of this Physician.
        :type firstname: str
        """

        self._firstname = firstname

    @property
    def surname(self):
        """Gets the surname of this Physician.


        :return: The surname of this Physician.
        :rtype: str
        """
        return self._surname

    @surname.setter
    def surname(self, surname):
        """Sets the surname of this Physician.


        :param surname: The surname of this Physician.
        :type surname: str
        """

        self._surname = surname

    @property
    def specialty(self):
        """Gets the specialty of this Physician.


        :return: The specialty of this Physician.
        :rtype: str
        """
        return self._specialty

    @specialty.setter
    def specialty(self, specialty):
        """Sets the specialty of this Physician.


        :param specialty: The specialty of this Physician.
        :type specialty: str
        """

        self._specialty = specialty

    @property
    def license_number(self):
        """Gets the license_number of this Physician.


        :return: The license_number of this Physician.
        :rtype: str
        """
        return self._license_number

    @license_number.setter
    def license_number(self, license_number):
        """Sets the license_number of this Physician.


        :param license_number: The license_number of this Physician.
        :type license_number: str
        """

        self._license_number = license_number

    @property
    def license_date(self):
        """Gets the license_date of this Physician.


        :return: The license_date of this Physician.
        :rtype: date
        """
        return self._license_date

    @license_date.setter
    def license_date(self, license_date):
        """Sets the license_date of this Physician.


        :param license_date: The license_date of this Physician.
        :type license_date: date
        """

        self._license_date = license_date
