# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class HIC(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, healthcare_provider_id=None, name=None, start_date=None, end_date=None):  # noqa: E501
        """HIC - a model defined in OpenAPI

        :param healthcare_provider_id: The healthcare_provider_id of this HIC.  # noqa: E501
        :type healthcare_provider_id: str
        :param name: The name of this HIC.  # noqa: E501
        :type name: str
        :param start_date: The start_date of this HIC.  # noqa: E501
        :type start_date: date
        :param end_date: The end_date of this HIC.  # noqa: E501
        :type end_date: date
        """
        self.openapi_types = {
            'healthcare_provider_id': str,
            'name': str,
            'start_date': date,
            'end_date': date
        }

        self.attribute_map = {
            'healthcare_provider_id': 'healthcare_provider_id',
            'name': 'name',
            'start_date': 'start_date',
            'end_date': 'end_date'
        }

        self._healthcare_provider_id = healthcare_provider_id
        self._name = name
        self._start_date = start_date
        self._end_date = end_date

    @classmethod
    def from_dict(cls, dikt) -> 'HIC':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The HIC of this HIC.  # noqa: E501
        :rtype: HIC
        """
        return util.deserialize_model(dikt, cls)

    @property
    def healthcare_provider_id(self):
        """Gets the healthcare_provider_id of this HIC.


        :return: The healthcare_provider_id of this HIC.
        :rtype: str
        """
        return self._healthcare_provider_id

    @healthcare_provider_id.setter
    def healthcare_provider_id(self, healthcare_provider_id):
        """Sets the healthcare_provider_id of this HIC.


        :param healthcare_provider_id: The healthcare_provider_id of this HIC.
        :type healthcare_provider_id: str
        """

        self._healthcare_provider_id = healthcare_provider_id

    @property
    def name(self):
        """Gets the name of this HIC.


        :return: The name of this HIC.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this HIC.


        :param name: The name of this HIC.
        :type name: str
        """

        self._name = name

    @property
    def start_date(self):
        """Gets the start_date of this HIC.


        :return: The start_date of this HIC.
        :rtype: date
        """
        return self._start_date

    @start_date.setter
    def start_date(self, start_date):
        """Sets the start_date of this HIC.


        :param start_date: The start_date of this HIC.
        :type start_date: date
        """

        self._start_date = start_date

    @property
    def end_date(self):
        """Gets the end_date of this HIC.


        :return: The end_date of this HIC.
        :rtype: date
        """
        return self._end_date

    @end_date.setter
    def end_date(self, end_date):
        """Sets the end_date of this HIC.


        :param end_date: The end_date of this HIC.
        :type end_date: date
        """

        self._end_date = end_date
