# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class Patient(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, client_id=None, firstname=None, surname=None, gender=None, dob=None, service_language=None, profile_start_date=None, profile_end_date=None, health_card_number=None, active_primary_physician_id=None, dietary_regimen=None, advance_directives=None):  # noqa: E501
        """Patient - a model defined in OpenAPI

        :param client_id: The client_id of this Patient.  # noqa: E501
        :type client_id: str
        :param firstname: The firstname of this Patient.  # noqa: E501
        :type firstname: str
        :param surname: The surname of this Patient.  # noqa: E501
        :type surname: str
        :param gender: The gender of this Patient.  # noqa: E501
        :type gender: GenderType
        :param dob: The dob of this Patient.  # noqa: E501
        :type dob: date
        :param service_language: The service_language of this Patient.  # noqa: E501
        :type service_language: ServiceLanguage
        :param profile_start_date: The profile_start_date of this Patient.  # noqa: E501
        :type profile_start_date: date
        :param profile_end_date: The profile_end_date of this Patient.  # noqa: E501
        :type profile_end_date: date
        :param health_card_number: The health_card_number of this Patient.  # noqa: E501
        :type health_card_number: str
        :param active_primary_physician_id: The active_primary_physician_id of this Patient.  # noqa: E501
        :type active_primary_physician_id: str
        :param dietary_regimen: The dietary_regimen of this Patient.  # noqa: E501
        :type dietary_regimen: List[DietaryRegimen]
        :param advance_directives: The advance_directives of this Patient.  # noqa: E501
        :type advance_directives: List[str]
        """
        self.openapi_types = {
            'client_id': str,
            'firstname': str,
            'surname': str,
            'gender': GenderType,
            'dob': date,
            'service_language': ServiceLanguage,
            'profile_start_date': date,
            'profile_end_date': date,
            'health_card_number': str,
            'active_primary_physician_id': str,
            'dietary_regimen': List[DietaryRegimen],
            'advance_directives': List[str]
        }

        self.attribute_map = {
            'client_id': 'client_id',
            'firstname': 'firstname',
            'surname': 'surname',
            'gender': 'gender',
            'dob': 'dob',
            'service_language': 'service_language',
            'profile_start_date': 'profile_start_date',
            'profile_end_date': 'profile_end_date',
            'health_card_number': 'health_card_number',
            'active_primary_physician_id': 'active_primary_physician_id',
            'dietary_regimen': 'dietary_regimen',
            'advance_directives': 'advance_directives'
        }

        self._client_id = client_id
        self._firstname = firstname
        self._surname = surname
        self._gender = gender
        self._dob = dob
        self._service_language = service_language
        self._profile_start_date = profile_start_date
        self._profile_end_date = profile_end_date
        self._health_card_number = health_card_number
        self._active_primary_physician_id = active_primary_physician_id
        self._dietary_regimen = dietary_regimen
        self._advance_directives = advance_directives

    @classmethod
    def from_dict(cls, dikt) -> 'Patient':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Patient of this Patient.  # noqa: E501
        :rtype: Patient
        """
        return util.deserialize_model(dikt, cls)

    @property
    def client_id(self):
        """Gets the client_id of this Patient.


        :return: The client_id of this Patient.
        :rtype: str
        """
        return self._client_id

    @client_id.setter
    def client_id(self, client_id):
        """Sets the client_id of this Patient.


        :param client_id: The client_id of this Patient.
        :type client_id: str
        """

        self._client_id = client_id

    @property
    def firstname(self):
        """Gets the firstname of this Patient.


        :return: The firstname of this Patient.
        :rtype: str
        """
        return self._firstname

    @firstname.setter
    def firstname(self, firstname):
        """Sets the firstname of this Patient.


        :param firstname: The firstname of this Patient.
        :type firstname: str
        """

        self._firstname = firstname

    @property
    def surname(self):
        """Gets the surname of this Patient.


        :return: The surname of this Patient.
        :rtype: str
        """
        return self._surname

    @surname.setter
    def surname(self, surname):
        """Sets the surname of this Patient.


        :param surname: The surname of this Patient.
        :type surname: str
        """

        self._surname = surname

    @property
    def gender(self):
        """Gets the gender of this Patient.


        :return: The gender of this Patient.
        :rtype: GenderType
        """
        return self._gender

    @gender.setter
    def gender(self, gender):
        """Sets the gender of this Patient.


        :param gender: The gender of this Patient.
        :type gender: GenderType
        """

        self._gender = gender

    @property
    def dob(self):
        """Gets the dob of this Patient.


        :return: The dob of this Patient.
        :rtype: date
        """
        return self._dob

    @dob.setter
    def dob(self, dob):
        """Sets the dob of this Patient.


        :param dob: The dob of this Patient.
        :type dob: date
        """

        self._dob = dob

    @property
    def service_language(self):
        """Gets the service_language of this Patient.


        :return: The service_language of this Patient.
        :rtype: ServiceLanguage
        """
        return self._service_language

    @service_language.setter
    def service_language(self, service_language):
        """Sets the service_language of this Patient.


        :param service_language: The service_language of this Patient.
        :type service_language: ServiceLanguage
        """

        self._service_language = service_language

    @property
    def profile_start_date(self):
        """Gets the profile_start_date of this Patient.

        a new client profile may start when they change names or gender  # noqa: E501

        :return: The profile_start_date of this Patient.
        :rtype: date
        """
        return self._profile_start_date

    @profile_start_date.setter
    def profile_start_date(self, profile_start_date):
        """Sets the profile_start_date of this Patient.

        a new client profile may start when they change names or gender  # noqa: E501

        :param profile_start_date: The profile_start_date of this Patient.
        :type profile_start_date: date
        """

        self._profile_start_date = profile_start_date

    @property
    def profile_end_date(self):
        """Gets the profile_end_date of this Patient.

        a client profile may end when they change names or gender  # noqa: E501

        :return: The profile_end_date of this Patient.
        :rtype: date
        """
        return self._profile_end_date

    @profile_end_date.setter
    def profile_end_date(self, profile_end_date):
        """Sets the profile_end_date of this Patient.

        a client profile may end when they change names or gender  # noqa: E501

        :param profile_end_date: The profile_end_date of this Patient.
        :type profile_end_date: date
        """

        self._profile_end_date = profile_end_date

    @property
    def health_card_number(self):
        """Gets the health_card_number of this Patient.


        :return: The health_card_number of this Patient.
        :rtype: str
        """
        return self._health_card_number

    @health_card_number.setter
    def health_card_number(self, health_card_number):
        """Sets the health_card_number of this Patient.


        :param health_card_number: The health_card_number of this Patient.
        :type health_card_number: str
        """

        self._health_card_number = health_card_number

    @property
    def active_primary_physician_id(self):
        """Gets the active_primary_physician_id of this Patient.


        :return: The active_primary_physician_id of this Patient.
        :rtype: str
        """
        return self._active_primary_physician_id

    @active_primary_physician_id.setter
    def active_primary_physician_id(self, active_primary_physician_id):
        """Sets the active_primary_physician_id of this Patient.


        :param active_primary_physician_id: The active_primary_physician_id of this Patient.
        :type active_primary_physician_id: str
        """

        self._active_primary_physician_id = active_primary_physician_id

    @property
    def dietary_regimen(self):
        """Gets the dietary_regimen of this Patient.

        the dietary aversions, restrictions, or preferences  # noqa: E501

        :return: The dietary_regimen of this Patient.
        :rtype: List[DietaryRegimen]
        """
        return self._dietary_regimen

    @dietary_regimen.setter
    def dietary_regimen(self, dietary_regimen):
        """Sets the dietary_regimen of this Patient.

        the dietary aversions, restrictions, or preferences  # noqa: E501

        :param dietary_regimen: The dietary_regimen of this Patient.
        :type dietary_regimen: List[DietaryRegimen]
        """

        self._dietary_regimen = dietary_regimen

    @property
    def advance_directives(self):
        """Gets the advance_directives of this Patient.


        :return: The advance_directives of this Patient.
        :rtype: List[str]
        """
        return self._advance_directives

    @advance_directives.setter
    def advance_directives(self, advance_directives):
        """Sets the advance_directives of this Patient.


        :param advance_directives: The advance_directives of this Patient.
        :type advance_directives: List[str]
        """

        self._advance_directives = advance_directives
